<a href="https://colab.research.google.com/github/Dayle227/Linear-Algebra/blob/master/Ricafrente_met.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.
$$\theta = 5x + 3y - z$$



In [10]:
import numpy as np


In [11]:
Θ = np.array([5, 3, -1])
print(Θ)

[ 5  3 -1]



2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

In [15]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [16]:
A = np.array([
    [1, 2, 1],
    [0, 4, -1],
    [0, 0, 10]
])
describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2




3. Given the matrix below, express it as a linear combination in a markdown.

In [17]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
G = np.diag(G)
G

array([1, 2, 7])

$$ x + 2y + 7z$$

# 4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [19]:
H = np.tril(G)
H

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 7]])

$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix} 
$$


$$
H= \left\{
    \begin{array}\\
        x \\ 
        2x + 2y \\
        4x + 6y + 7z
    \end{array}
\right. \\
 $$
 